@startuml "Consultar seguimiento de bolsin"

skinparam pageSize 420mm 297mm
skinparam pageOrientation landscape
skinparam dpi 150
skinparam scale 0.55
skinparam pageMargin 5

skinparam ParticipantPadding 2
skinparam BoxPadding 2
skinparam Padding 1

skinparam ranksep 10
skinparam nodesep 5

skinparam maxMessageSize 40
skinparam sequenceMessageAlign left
skinparam shadowing false

hide footbox

actor "Encargado de Bolsin" as EB
boundary "Pantalla Bolsin" as PSB
control "Gestor Bolsin" as GB

create PSB
EB -->  PSB : opcionConsultarUbicacion()

PSB -> PSB : habilitarPantalla()

create GB
PSB --> GB : consultarUbicacion()

' Encontrar el empleado loguado
entity "Actual:Sesion" as AS
entity ":Empleado" as EMP
entity "Logueado:Empleado" as LE
entity "ComisionMedica" as CM

GB -> GB : buscarEmpleadoLogueado()
GB -> AS : getUsuario()
loop Mientras existan empleados
    GB -> EMP : esTuUsuario()
end

' Buscamos la CM del empleado logueado
GB -> GB : buscarCMEmpleadoLogueado()
GB -> LE : getCM()
LE -> CM : getNombre()
GB -> PSB : mostrarNombreCM()

' Buscamos los Bolsines enviados
entity "Bolsin" as B
entity "Cambio Estado" as CE
entity "Actual:Cambio Estado" as ACE
entity "Estado" as EST

GB -> GB : buscarBolsinesEnviadosEnCM()

loop mientras exista bolsines
     GB -> B : esCMOrigenIgualCMEmpleado()
     GB -> B : sosEnviado()
     B -> B : buscarCambioEstadoActual()

        loop mientras exista cambios de estado
         B -> CE : sosActual()
        end

     B -> ACE : sosEnviado()
     ACE -> EST : esEnviado()
end

GB -> GB : buscaDatosBolsines()
loop mientras exista bolsines 
    GB -> B : getNumeroBolsin()
    GB -> B : getCMDestino()
end

' GPS
boundary "Interfaz GPS" as IGPS
actor "GPS Tracker" as AGPS

GB -> GB : buscarLocalizacion()
create IGPS
GB --> IGPS : solicitarLocalizacion()
    loop mientras existan bolsines
        IGPS -> AGPS : getBolsinLocation()
    end

' Google Maps
GB -> GB : buscarMapa()
boundary "Interfaz Mapa" as IM
actor "Servidor Google Maps" as AGM

create IM
GB --> IM : solicitarMapa()
IM -> AGM : solicitarMapa()
GB -> PSB : mostrarMapaPosicionBolsines()

' Seleccion de tipo de busqueda
PSB -> PSB : habilitarFormasBusqueda()
' GB -> PSB : solicitarSeleccionBusqueda()
' EB -> PSB : tomarSeleccionBusqueda()
' PSB -> GB : tomarSeleccionBusqueda()

' ' Seleccion del bolsin
' GB -> IB : solicitarSeleccionBolsinMapa()
EB -> PSB : tomarSeleccionBolsinMapa()
PSB -> GB : tomarSeleccionBolsinMapa()

' ' Solicitud para enviar email
GB -> PSB : solicitarConfirmacionEnviarCorreo()
EB -> PSB : tomarConfirmacionEnviarCorreo()
PSB -> GB : tomarConfirmacionEnviarCorreo()


' Buscar al mail del GCM
entity ":Rol" as R
entity "Gerente:Empleado"  as GE
GB -> GB : buscarGCM()
    loop mientras existan empleados
    GB -> EMP : esTuCM()
    GB -> EMP : sosGCM()
    EMP -> R : esGCM()
    end

GB -> GB : buscarEmailGCM()
GB -> GE : getEmail()

' Llamar caso de uso 31.Notificar ubicacion de bolsin
Entity "NotificarUbicacionBolsin:CU" as NUB
GB --> NUB : include()

GB -> PSB : mostrarEjecucionExitosa()
GB -> GB : finCU()
@enduml